config/routes.rb
Rails.application.routes.draw do
  resources :annonces 

  root 'annonces#index'
  get '/result', to: 'annonces#result'

end

app/models/annonce.rb
class Annonce < ActiveRecord::Base
	validates :titre, :adresse, :dispo, :quantite, presence: true
	validates :code_postal, presence: true, length: { is: 5 }, :numericality => true

	def self.search(cat, code_postal)
		if is_tout?(cat)
			if is_partout?(code_postal)
				all.order(dispo: :asc)
			else
				if code_postal.length == 5
					where(code_postal: code_postal).order(dispo: :asc)
				else
					Annonce.find_by_sql("
						SELECT * 
						FROM annonces 
						WHERE annonces.code_postal LIKE '#{code_postal}%' 
						ORDER BY annonces.dispo ASC")
				end
			end
		else
			if is_partout?(code_postal)
				where(categorie: cat).order(dispo: :asc)
			else
				if code_postal.length == 5
					where(categorie: cat, code_postal: code_postal).order(dispo: :asc)
				else
					Annonce.find_by_sql("
						SELECT * 
						FROM annonces 
						WHERE annonces.code_postal LIKE '#{code_postal}%' AND annonces.categorie = '#{cat}'
						ORDER BY annonces.dispo ASC")
				end
			end			
		end
 	end

 	def self.is_tout?(cat)
 		cat == 'Tout'
 	end

 	def self.is_partout?(code_postal)
 		code_postal == ''
 	end

	def self.search_other(cat, code_postal)
		if !is_tout?(cat) && !is_partout?(code_postal)
			if code_postal.length == 5
				Annonce.find_by_sql("
					SELECT * 
					FROM annonces 
					WHERE annonces.code_postal = '#{code_postal}' AND annonces.categorie != '#{cat}' 
					ORDER BY annonces.dispo ASC")
			else
				Annonce.find_by_sql("
					SELECT * 
					FROM annonces 
					WHERE annonces.code_postal LIKE '#{code_postal}%' AND annonces.categorie != '#{cat}' 
					ORDER BY annonces.dispo ASC")
			end
		end
	end

end

app/models/codes_postaux_et_commune.rb
class CodesPostauxEtCommune < ActiveRecord::Base
end

app/controllers/annonces_controller.rb
class AnnoncesController < ApplicationController
	def new
		@annonce = Annonce.new
		@villes = CodesPostauxEtCommune.all
	end

	def create
		@annonce = Annonce.new(annonce_params)
		@villes = CodesPostauxEtCommune.all
		if @annonce.save
			flash[:notice] = "Votre annonce a été déposée. Merci."
			redirect_to @annonce
  		else
    		render 'new'
  		end
  	end	

	def index
		@annonces = Annonce.last(3).reverse
	end

	def show
	    @annonce = Annonce.find(params[:id])
 	end	

 	def result		
 		@annonces = Annonce.search(params[:search], params[:code_postal])
		@autres_categories = Annonce.search_other(params[:search], params[:code_postal])
 	end

	private
	  def annonce_params
	    params.require(:annonce).permit(:categorie,:titre,:code_postal,:adresse,:dispo,:quantite,:commentaire, :img, :don)
	  end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :save_url

  def save_url
    # here you should save request.original_url
  end
end

app/helpers/annonces_helper.rb
module AnnoncesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/annonces/_addbar.erb
<h2>Proposez quelque chose</h2>
<div>
	<%= link_to 'Cliquez ici', new_annonce_path, :class => "btn_search" %>
</div>

app/views/annonces/_affichage_annonces.erb
<h3>Les trois dernières annonces deposées</h3>
<div class="dernieres_annonces">
<% @annonces.each do |annonce| %>
	<div class="classement">
		<div class="code_postale">
		<%= annonce.code_postal %>
		</div>
		<%= annonce.categorie %><br>
		<div class="titre_annonce">
			<%= annonce.titre %>
		</div>
		<%= annonce.adresse %><br>
		<%= annonce.quantite %><br>
		<%= annonce.commentaire %><br>
	</div>
<% end %>
</div>

app/views/annonces/_searchbar.erb
<h2>Cherchez quelque chose</h2>	
<div class="align_right">
	<%= form_tag '/result', :method => 'get' do %>
		<div>
			<%= label_tag :"Quoi ?" %>
	    	<%= select_tag :search,options_for_select([ "Tout", "Fruits", "Légumes", "Autres" ], params[:search]), :class =>"btn_search" %>
	    	</div>
	    	<div>
	    	<%= label_tag :"Où ?" %>
	    	<%= text_field_tag :code_postal, params[:code_postal], placeholder: 'code postal ou n°départ', :class =>"btn_search" %>
		</div>
		<div>
			<%= submit_tag "Chercher", :name => nil, :class => 'btn_search' %>
		</div>
	<% end %>
</div>

app/views/annonces/index.erb
<div class="accueil_container">
	<div class="intro">
		<p>Trop de fruits, mais pas assez de légumes ?</p>
		<p>Troquez !</p>
	</div>
	<div class="titre">
		<p>TROC DE JARDIN</p>
	</div>
	<div class="accueil_choix">
		<div class= "accueil_depot">
			<%= render "annonces/addbar" %>
		</div>
		<div class= "accueil_search">
			<%= render "annonces/searchbar" %>
		</div>
	</div>
</div>

app/views/annonces/new.erb
<%= render "layouts/nav" %>
<% ville_canton = [] %>
<div class="affichage">
	<h2>Nouvelle annonce</h2>
		
		<%= form_for :annonce, url: annonces_path  do |f| %>
			    <div class="form_annonce">
			    	<%= f.label :catégorie %>
			    	<%= f.select( :categorie, ['Fruits', "Légumes", "Autres"], {}, { :class => 'input_select' }) %>
			    </div>
			    <div class="form_annonce">
			    	<%= f.label :"titre :" %>
			    	<%= f.text_field :titre, :class =>"input_form"%>
			    </div>
			    <div class="form_annonce">
			    	<%= f.label :"code postal :" %>
			    	<%= f.text_field :code_postal, :class =>'input_form' %>
			    </div>

				<% recup_cp = "" %>
			    	<% @villes.each do |ville| %>
					<% recup_cp = f.text_field :code_postal  %>
			    		<% if ville.CodePostal == "'"+ recup_cp[26,5]+"'" %>
			    			<% ville_canton << ville.NomMinPoste[1..ville.NomMinPoste.length-2] %>	
			    		<% end %>
			    	<% end %>

			    <div class="form_annonce">
			    	<%= f.label :ville %>
			    	<%= f.select( :img, ville_canton, {}, { :class => 'input_select' }) %>
			    </div>

			    <div class="form_annonce">
			    	<%= f.label :"adresse e-mail :" %>
			    	<%= f.text_field :adresse, :class =>"input_form" %>
			    </div>
			    <div class="form_annonce">
			    	<%= f.label :"quantité :" %>
			    	<%= f.text_field :quantite, :class =>"input_form" %>
			    </div>
			    <div class="form_annonce">
			    	<%= f.label :"commentaire :" %>
			    	<%= f.text_area :commentaire, :class =>"input_form" %>
			    </div>
			    <div class="form_annonce">
			    	<%= f.label :"date de disponibilité :" %>
			    	<div>
			    	<%= f.date_select :dispo, {:order => [:day, :month, :year], :use_month_names => [t(:Janvier), t(:Février), t(:Mars), t(:Avril), t(:Mai), t(:Juin), t(:Juillet), t(:Août), t(:Septembre), t(:Octobre), t(:Novembre), t(:Décembre)]}, {:class => 'input_select_date' } %>
			    	</div>
			    </div>
			    <div>
			    	<%= f.submit 'Valider', :class =>"validation" %>
			    </div>	
		<% end %>
</div>

app/views/annonces/result.erb
<%= render "layouts/nav" %>


<div class="result_annonces">
	<% if @annonces.blank? %>
		<h3>Aucune annonce correspondante</h3><br>
	<% end %>
	<% @annonces.each do |annonces| %>
			<div class="classement_result">
				<div class="titre_annonce">
					<%= link_to annonce_path(annonces.id), class: "liens"  do %>
					<%= annonces.titre %>
				</div>
					<%= label_tag :"Quantité :" %>
					<%= annonces.quantite %><br>
					<%= label_tag :"Date de disponibilité :" %>
					<%= annonces.dispo.strftime('%d/%m/%y') %>
					<div class="code_postale">
						<%= annonces.code_postal %>
						<%= annonces.img %>
					</div>
			</div>
		<% end %>
	<% end %>

	<% if @autres_categories.present? %>
		<h3>Les autres offres de la région</h3>
		<% @autres_categories.each do |annonces| %>
				<div class="classement_result">
					<div class="titre_annonce">
						<%= link_to annonce_path(annonces.id), class: "liens"  do %>
						<%= annonces.titre %>
					</div>
					<%= label_tag :"Quantité :" %>
					<%= annonces.quantite %><br>
					<%= label_tag :"Date de disponibilité :" %>
					<%= annonces.dispo.strftime('%d/%m/%y') %>
					<div class="code_postale">
						<%= annonces.code_postal %>
						<%= annonces.img %>
					</div>
				</div>
			<% end %>
		<% end %>
	<% end %>
</div>

app/views/annonces/show.erb
<%= render "layouts/nav" %>
<div class="result_annonces">
	<h2>Annonce</h2>
	<div class="classement_result">
		<div class="titre_annonce">
			<%= @annonce.titre %><br>
		</div>
		<p>Quantité : <%= @annonce.quantite %></p>
		<p>Date de disponibilité : <%= @annonce.dispo.strftime('%d/%m/%y') %></p><br>
		<p><%= @annonce.commentaire %></p><br>
		<%= @annonce.adresse %><br>
		<div class="code_postale">
			<%= @annonce.code_postal %>
			<%= @annonce.img %>
		</div><br>	
		<% if flash[:notice] %>
			<h2><%= flash[:notice] %></h2><br>
			<button>
				<a class="liens" href="/annonces"><h3>Retour à l'accueil</h3></a>
			</button>
		<% else %>
			<button>
				<a class="liens" href="javascript:history.back()"><h3>Retour à votre recherche</h3></a>
			</button>
		<% end %>
	</div>
</div>

app/views/layouts/_nav.html.erb
<nav class= "navbar">
	<ul>
		<li>
			<%= link_to image_tag("pom1.svg"), annonces_path %>
		</li>
		<li class="menu">
			<%= link_to 'Proposez quelque chose', new_annonce_path %>
		</li>
		<div class="search">
			<li class="menu"><a href="#"><%= image_tag ("hamburg2.svg") %><p>Recherche</p></a>
				<ul>
					<%= form_tag '/result', :method => 'get' do %>
						<li>
							<%= label_tag :"Quoi ?" %>
							<%= select_tag :search,options_for_select([ "Tout", "Fruits", "Légumes", "Autres" ], params[:search]) %>
						</li>
						<li>
							<%= label_tag :"Où ?" %>
							<%= text_field_tag :code_postal, params[:code_postal], placeholder: 'code postal ou n°dépt' %>
						</li>
						<li>
							<%= submit_tag "Chercher", :name => nil, :class =>'btn_search' %>
						</li>
					<% end %>
				</ul>
			</li>
		</div>
	</ul>
</nav>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jardins</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>